node.name: elasticsearch-01
cluster.name: es-myapp-cluster
network.host: 0.0.0.0
discovery.seed_hosts: elasticsearch-02
cluster.initial_master_nodes: elasticsearch-01,elasticsearch-02
bootstrap.memory_lock: true
xpack.security.enabled: false