version: "3.9"

services:
  php:
    restart: always
    container_name: app-php
    build:
      context: ./images/php
      dockerfile: Dockerfile
    working_dir: /var/www
    expose:
      - ${PHP_INTERNAL_PORT:-9000}
    volumes:
      - ./www:/var/www
    environment:
      - APP_ENV=production
    networks:
      default:
        ipv4_address: 172.20.0.10

  web:
    restart: always
    container_name: app-nginx
    build:
      context: ./images/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      default:
        ipv4_address: 172.20.0.20

  #Check requirements from app-php
  postgresql:
    restart: always
    container_name: app-postgresql
    build:
      context: ./images/postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db_name}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    ports:
      - '5432:5432'
    volumes:
      - ./images/postgresql/data:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.20.0.30

  #Check requirements from app-php
  mysql:
    restart: always
    container_name: app-mysql
    build:
      context: ./images/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db_name}
      MYSQL_USER: ${MYSQL_USER:-db_user_name}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123456}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-12346789}
    ports:
      - "3306:3306"
    volumes:
      - ./images/mysql/data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.20.0.35

  redis:
    restart: always
    container_name: app-redis
    build:
      context: ./images/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    networks:
      default:
        ipv4_address: 172.20.0.40

networks:
  default:
    driver: bridge
    name: default_network
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  myapp:
    driver: local