version: "3.9"

services:
  php:
    restart: always
    container_name: app-php
    build:
      context: ./docker/images/php
      dockerfile: Dockerfile
    working_dir: /var/www/html
    expose:
      - ${PHP_INTERNAL_PORT:-9000}
    volumes:
      - ./:/var/www/html
    networks:
      default:
        ipv4_address: 172.20.0.10

  web:
    restart: always
    container_name: app-nginx
    build:
      context: ./docker/images/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      default:
        ipv4_address: 172.20.0.20

  #PHP > Dockerfile göre gerekli kütüphaneleri ayarlanması gerekir. Default olarak postgresql alınmıştır.
  postgresql:
    restart: always
    container_name: app-postgresql
    build:
      context: ./docker/images/postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db_name}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    ports:
      - '5432:5432'
    volumes:
      - ./docker/images/postgresql/data:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.20.0.30

  #PHP > Dockerfile göre gerekli kütüphaneleri ayarlanması gerekir. Mysql kullanacaksanız PHP Dockerfile kütüphanelerini düzeltiniz.
  #  mysql:
  #    restart: always
  #    container_name: app-mysql
  #    build:
  #      context: ./docker/images/mysql
  #      dockerfile: Dockerfile
  #    environment:
  #      MYSQL_DATABASE: ${MYSQL_DATABASE:-db_name}
  #      MYSQL_USER: ${MYSQL_USER:-db_user_name}
  #      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123456}
  #      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-12346789}
  #    ports:
  #      - "3306:3306"
  #    volumes:
  #      - ./images/mysql/data:/var/lib/mysql
  #    networks:
  #      default:
  #        ipv4_address: 172.20.0.35

  redis:
    restart: always
    container_name: app-redis
    build:
      context: ./docker/images/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - ./docker/images/redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-123456}
    networks:
      default:
        ipv4_address: 172.20.0.40

  rabbitmq:
    restart: always
    container_name: app-rabbitmq
    build:
      context: ./docker/images/rabbitmq
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker/images/rabbitmq/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-/}
    networks:
      default:
        ipv4_address: 172.20.0.50

  mongodb:
    restart: always
    container_name: app-mongodb
    build:
      context: ./docker/images/mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./docker/images/mongodb/data/db:/data/db
      - ./docker/images/mongodb/data/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-mongoadmin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mongoadmin}
    networks:
      default:
        ipv4_address: 172.20.0.60

  #Eğer istiyorsanız mangodb GUI tool olarak mongo express kullanabiliriz.
  mongo-express:
    depends_on:
      - mongodb
    restart: always
    container_name: app-mongo-express
    build:
      context: ./docker/images/mongo-express
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-mongoadmin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mongoadmin}
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      default:
        ipv4_address: 172.20.0.70

  #ELK Multi-node cluster
  elasticsearch-setup:
    container_name: app-elasticsearch-setup
    build:
      context: ./docker/images/elasticsearch
      args:
        ELK_VERSION: ${ELK_VERSION}
      dockerfile: Dockerfile
    volumes:
      - ./docker/images/elasticsearch/certs:/usr/share/elasticsearch/config/certs:z
      - ./docker/images/elasticsearch/config/setup/instances.yml:/usr/share/elasticsearch/config/certs/instances.yml
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        find . -type d -exec chmod 750 \{\} \;;
        find . -type f -exec chmod 640 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://elasticsearch-01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u elastic:${ELASTIC_PASSWORD} -H "Content-Type: application/json" https://elasticsearch-01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 30; done;
        echo "All done!";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/elasticsearch-01/elasticsearch-01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  elasticsearch-01:
    depends_on:
      elasticsearch-setup:
        condition: service_healthy
    restart: always
    container_name: app-elasticsearch-01
    build:
      context: ./docker/images/elasticsearch
      args:
        ELK_VERSION: ${ELK_VERSION}
      dockerfile: Dockerfile
    environment:
      node.name: elasticsearch-01
      cluster.name: es-myapp-cluster
      network.host: 0.0.0.0 #herhangi bir ip den bilgi alabilmesi için belirlenmiştir. Default'dur
      discovery.seed_hosts: elasticsearch-02 #,elasticsearch-02,... #Dikkat kendi servisi eklenmemelidir. #Diğer uygun düğümlerin bulunmasını sağlarız.
      cluster.initial_master_nodes: elasticsearch-01,elasticsearch-02 #Ana elasticsearch servislerinin hepsi yazılır. Sebebi bir ana düğüm çöktüğünde diğer düğümler devam etmelidir.
      bootstrap.memory_lock: true # İşletim sistemini yaptığı fazla bellek kullanmak ve kullanılmayan belleği örneğin disk ile memory swap(takas/değişim) için kullanması gibi şeyler performansı düşürdüğünden değişimi kapatmak ve elasticsearch performans için true önerilir.
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: "-Xms512m -Xmx512m" #Java parametreleridir. -Xms512m (min heap memory) -Xmx512m (Heap’in max heap memory) # Düğümün kullanılmasına izin verilen min ve maks ram miktarının belirlenmesidir.

      # Security
      xpack.security.enabled: true
      xpack.security.http.ssl.enabled: true
      xpack.security.http.ssl.key: certs/elasticsearch-01/elasticsearch-01.key
      xpack.security.http.ssl.certificate: certs/elasticsearch-01/elasticsearch-01.crt
      xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt
      xpack.security.http.ssl.verification_mode: certificate
      xpack.security.transport.ssl.enabled: true
      xpack.security.transport.ssl.key: certs/elasticsearch-01/elasticsearch-01.key
      xpack.security.transport.ssl.certificate: certs/elasticsearch-01/elasticsearch-01.crt
      xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.license.self_generated.type: ${ELASTIC_LICENSE}

    #Geliştirme veya test ortamı için kullanılabilir hazır ayar. Sadece tek elasticsearch servisi olmalıdır.
#    environment:
#      - node.name=node01
#      - cluster.name=es-myapp-cluster
#      - discovery.type=single-node #bazı configuration atlamaktadır.
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9300:9300" # port 9300 for communication between nodes within the cluster (Required)
      - "9200:9200" # port 9200 for requests (Optional)
    volumes:
      - ./docker/images/elasticsearch/data/01:/usr/share/elasticsearch/data #elasticsearch Data
      - ./docker/images/elasticsearch/certs:/usr/share/elasticsearch/config/certs #elasticsearch Certificates
    networks:
      default:
        ipv4_address: 172.20.0.80

  elasticsearch-02:
    depends_on:
      elasticsearch-setup:
        condition: service_healthy
    restart: always
    container_name: app-elasticsearch-02
    build:
      context: ./docker/images/elasticsearch
      args:
        ELK_VERSION: ${ELK_VERSION}
      dockerfile: Dockerfile
    environment:
      node.name: elasticsearch-02
      cluster.name: es-myapp-cluster
      network.host: 0.0.0.0
      discovery.seed_hosts: elasticsearch-01
      cluster.initial_master_nodes: elasticsearch-01,elasticsearch-02
      bootstrap.memory_lock: true
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

      # Security
      xpack.security.enabled: true
      xpack.security.http.ssl.enabled: true
      xpack.security.http.ssl.key: certs/elasticsearch-02/elasticsearch-02.key
      xpack.security.http.ssl.certificate: certs/elasticsearch-02/elasticsearch-02.crt
      xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt
      xpack.security.http.ssl.verification_mode: certificate
      xpack.security.transport.ssl.enabled: true
      xpack.security.transport.ssl.key: certs/elasticsearch-02/elasticsearch-02.key
      xpack.security.transport.ssl.certificate: certs/elasticsearch-02/elasticsearch-02.crt
      xpack.security.transport.ssl.certificate_authorities: certs/ca/ca.crt
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.license.self_generated.type: ${ELASTIC_LICENSE}

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/images/elasticsearch/data/02:/usr/share/elasticsearch/data #elasticsearch Data
      - ./docker/images/elasticsearch/certs:/usr/share/elasticsearch/config/certs #elasticsearch Certificates
    networks:
      default:
        ipv4_address: 172.20.0.90

  kibana:
    depends_on:
      elasticsearch-setup:
        condition: service_healthy
    restart: always
    container_name: app-kibana
    build:
      context: ./docker/images/kibana
      args:
        ELK_VERSION: ${ELK_VERSION}
      dockerfile: Dockerfile
    volumes:
      - ./docker/images/elasticsearch/certs:/usr/share/kibana/config/certs
      - ./docker/images/kibana/data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://elasticsearch-01:9200
      - ELASTICSEARCH_USERNAME=${KIBANA_USERNAME}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
    networks:
      default:
        ipv4_address: 172.20.0.100

networks:
  default:
    driver: bridge
    name: default_network
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  myapp:
    driver: local