version: "3.9"

services:

  php:
    restart: always
    container_name: app-php
    
    build:
      context: ./php
      dockerfile: Dockerfile

    working_dir: /var/www

    expose:
      - 9000

    volumes:
      - ./www:/var/www

    env_file:
      - ./.env

    environment:
      - APP_ENV=production

    networks:
      default:
        ipv4_address: 172.20.0.20

  web:
    restart: always
    container_name: app-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"

networks:

  default:
    driver: bridge
    name: default_network
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  myapp_volume:
    driver: local